<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Implementation" nsURI="http:///Implementation.ecore" nsPrefix="Implementation">
  <eClassifiers xsi:type="ecore:EClass" name="DecisionSupportComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionSupportComponent_IDecisionSupport"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionSupportComponent_DSSProcessor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionSupportComponent_DSSPresenter"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionSupportComponent_DSSController"
      eSuperTypes="#//DecisionSupportComponent_IDecisionSupport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dSSProcessor" ordered="false"
        upperBound="-1" eType="#//DecisionSupportComponent_DSSProcessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dSSPresenter" ordered="false"
        lowerBound="1" eType="#//DecisionSupportComponent_DSSPresenter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iRoomDecision" ordered="false"
        lowerBound="1" eType="#//RoomComponent_IRoomDecision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iOccupancyDecision" ordered="false"
        lowerBound="1" eType="#//OccupancyComponent_IOccupancyDecision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iAdditionalServiceDecision"
        ordered="false" lowerBound="1" eType="#//AdditionalServiceComponent_IAdditionalServiceDecision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iBookingDecision" ordered="false"
        lowerBound="1" eType="#//BookingComponent_IBookingDecision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomComponent_IRoomDecision" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent_IOccupancyDecision"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent_IAdditionalServiceDecision"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BookingComponent_IBookingDecision" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent_Occupancy">
    <eOperations name="Occupancy" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="checkInDateTime" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="Guest" ordered="false" lowerBound="1" eType="#//OccupancyComponent_Guest"/>
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkInDateTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOutDateTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Guest" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//OccupancyComponent_Guest"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bookingReference" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guests" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//OccupancyComponent_Guest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent_Guest">
    <eOperations name="Guest" ordered="false" lowerBound="1">
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent_IOccupancy" abstract="true"
      interface="true">
    <eOperations name="checkInGuest" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="checkOutGuest" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="listFreeRooms" ordered="false" upperBound="-1" eType="ecore:EDataType types.ecore#//String"/>
    <eOperations name="listGuestsInRoom" ordered="false" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType types.ecore#//String">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="numberOfGuestsInHotel" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent_OccupancyHandler"
      eSuperTypes="#//OccupancyComponent_IOccupancyDecision #//OccupancyComponent_IOccupancy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iRoomInformation" ordered="false"
        lowerBound="1" eType="#//RoomComponent_IRoomInformation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iBooking" ordered="false"
        lowerBound="1" eType="#//BookingComponent_IBooking"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="occupancy" ordered="false"
        upperBound="-1" eType="#//OccupancyComponent_Occupancy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomComponent_IRoomInformation" abstract="true"
      interface="true">
    <eOperations name="getRoomInfo" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="searchRoom" ordered="false" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType types.ecore#//String">
      <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="getRoomTypes" ordered="false" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType types.ecore#//String"/>
    <eOperations name="getAllRoomNumbers" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eOperations name="countNumberOfTotalRooms" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookingComponent_IBooking" abstract="true"
      interface="true">
    <eOperations name="makeBooking" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="customerSSN" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="customerFirstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="customerLastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="customerAddress" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="customerEmail" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="addRoom" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="roomId" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="requestQuote" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="editBooking" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="roomId" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="customerId" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="cancelBooking" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="addAdditionalService" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="additionalServiceName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeRoom" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="roomId" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeAddionalService" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="additionalServiceName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="generateQuote" ordered="false" lowerBound="1">
      <eParameters name="startDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="endDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="searchForBooking" ordered="false" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType types.ecore#//String">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="addGuestToBooking" ordered="false" lowerBound="1">
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentComponent_PaymentManager" eSuperTypes="#//PaymentComponent_IPayment">
    <eOperations name="makePayment" ordered="false" lowerBound="1">
      <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="amount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="expireMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="isCreditCardValid" ordered="false" lowerBound="1">
      <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentDetails" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payments" ordered="false"
        upperBound="-1" eType="#//PaymentComponent_Payment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentComponent_Payment"/>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentComponent_IPayment" abstract="true"
      interface="true">
    <eOperations name="payForBooking" ordered="false" lowerBound="1">
      <eParameters name="amount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="reserveFunds" ordered="false" lowerBound="1">
      <eParameters name="amount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="unreserveFunds" ordered="false" lowerBound="1">
      <eParameters name="amount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent_AdditionalService"
      eSuperTypes="#//AdditionalServiceComponent_IAdditionalServiceDecision #//AdditionalServiceComponent_IAdditionalServiceInformation #//AdditionalServiceComponent_IAdditionalServiceAdministration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usable" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAttendant" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iAuthentication" ordered="false"
        lowerBound="1" eType="#//StaffComponent_IAuthentication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaffComponent_IAuthentication" abstract="true"
      interface="true">
    <eOperations name="logIn" ordered="false" lowerBound="1">
      <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="logOut" ordered="false" lowerBound="1">
      <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="isLoggedIn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean">
      <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent_IAdditionalServiceInformation"
      abstract="true" interface="true">
    <eOperations name="getAdditionalServiceInfo" ordered="false" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType types.ecore#//String">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="getAllAdditionalServices" ordered="false" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent_IAdditionalServiceAdministration"
      abstract="true" interface="true">
    <eOperations name="createAdditionalService" ordered="false" lowerBound="1">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="maxAttendants" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="editAdditionalService" ordered="false" lowerBound="1">
      <eParameters name="oldName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="maxAttendants" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="removeAdditionalService" ordered="false" lowerBound="1">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent_AdditionalServiceEvent">
    <eOperations name="getAdditionalServiceInfo" ordered="false" lowerBound="1">
      <eParameters name="addtionalServiceName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAttendant" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookingComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="BookingComponent_PaymentDetails">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ccNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ccv" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expiryMonth" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expiryYear" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookingComponent_Booking">
    <eOperations name="Booking" ordered="false" lowerBound="1" eType="#//BookingComponent_Booking"/>
    <eOperations name="Booking" ordered="false" lowerBound="1" eType="#//BookingComponent_Booking">
      <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="addAdditionalServiceToBooking" ordered="false" lowerBound="1">
      <eParameters name="newService" ordered="false" lowerBound="1" eType="#//BookingComponent_AdditionalService"/>
    </eOperations>
    <eOperations name="Booking" ordered="false" lowerBound="1" eType="#//BookingComponent_Booking">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="customerSSN" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="customerFirstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="customerLastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="customerAddress" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="addRoomToBooking" ordered="false" lowerBound="1">
      <eParameters name="newRoom" ordered="false" lowerBound="1" eType="#//BookingComponent_RoomType"/>
    </eOperations>
    <eOperations name="removeRoomFromBooking" ordered="false" lowerBound="1">
      <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="updateBooking" ordered="false" lowerBound="1">
      <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="removeAdditionalServiceFromBooking" ordered="false" lowerBound="1">
      <eParameters name="additionalService" ordered="false" lowerBound="1" eType="#//BookingComponent_AdditionalService"/>
    </eOperations>
    <eOperations name="currentCost" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eOperations name="updatePaymentDetails" ordered="false" lowerBound="1">
      <eParameters name="newPaymentDetails" ordered="false" lowerBound="1" eType="#//BookingComponent_PaymentDetails"/>
    </eOperations>
    <eOperations name="generateReferenceNumber" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrivalDate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="departureDate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentCost" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalServices" ordered="false"
        upperBound="-1" eType="#//BookingComponent_AdditionalService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guests" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//BookingComponent_BookingGuest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paymentDetails" ordered="false"
        lowerBound="1" eType="#//BookingComponent_PaymentDetails"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//BookingComponent_RoomType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookingComponent_AdditionalService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookingComponent_BookingGuest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookingComponent_RoomType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomType" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookingComponent_BookingManager" eSuperTypes="#//BookingComponent_IBooking #//BookingComponent_IBookingDecision">
    <eOperations name="BookingManager" ordered="false" lowerBound="1"/>
    <eOperations name="findBooking" ordered="false" lowerBound="1" eType="#//BookingComponent_Booking">
      <eParameters name="referenceNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookings" ordered="false"
        upperBound="-1" eType="#//BookingComponent_Booking"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authentication" ordered="false"
        lowerBound="1" eType="#//StaffComponent_IAuthentication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iRoomInformation" ordered="false"
        lowerBound="1" eType="#//RoomComponent_IRoomInformation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iPayment" ordered="false"
        lowerBound="1" eType="#//PaymentComponent_IPayment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iAdditionalServiceInformation"
        ordered="false" lowerBound="1" eType="#//AdditionalServiceComponent_IAdditionalServiceInformation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaffComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="StaffComponent_AccountManager" eSuperTypes="#//StaffComponent_IAuthentication #//StaffComponent_IAccountAdministration">
    <eOperations name="findAccount" ordered="false" lowerBound="1" eType="#//StaffComponent_Employee">
      <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iAuthentication" ordered="false"
        lowerBound="1" eType="#//StaffComponent_IAuthentication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loggedIn" ordered="false"
        upperBound="-1" eType="#//StaffComponent_Employee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//StaffComponent_Employee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaffComponent_Employee">
    <eOperations name="Employee" ordered="false" lowerBound="1">
      <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="phone" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="Employee" ordered="false" lowerBound="1"/>
    <eOperations name="getEmployeeInfo" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaffComponent_IAccountAdministration"
      abstract="true" interface="true">
    <eOperations name="createAccount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="phone" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="editAccountDetails" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean">
      <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="phone" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="removeAccount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean">
      <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoomComponent_Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usable" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomTypeName" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomComponent_Bedroom" eSuperTypes="#//RoomComponent_Room">
    <eOperations name="createBedroom" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="bedCount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="editRoom" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="bedCount" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedCount" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomComponent_ConferenceRoom" eSuperTypes="#//RoomComponent_Room">
    <eOperations name="createConferenceRoom" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="numberOfSeats" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="projector" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      <eParameters name="conferenceRoom" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
    </eOperations>
    <eOperations name="editRoom" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="numberOfSeats" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="projector" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="conferencePhone" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSeats" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projector" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conferencePhone" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomComponent_IRoomAdministration" abstract="true"
      interface="true">
    <eOperations name="createRoom" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="editRoom" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="remove" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomComponent_RoomHandler" eSuperTypes="#//RoomComponent_IRoomDecision #//RoomComponent_IRoomInformation #//RoomComponent_IRoomAdministration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authenticator" ordered="false"
        lowerBound="1" eType="#//StaffComponent_IAuthentication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" ordered="false" lowerBound="1"
        upperBound="-1" eType="#//RoomComponent_Room"/>
  </eClassifiers>
</ecore:EPackage>
