<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Implementation" nsURI="http:///Implementation.ecore" nsPrefix="Implementation">
  <eSubpackages name="Dependencies" nsURI="http:///Implementation/Dependencies.ecore"
      nsPrefix="Implementation.Dependencies"/>
  <eSubpackages name="Components" nsURI="http:///Implementation/Components.ecore"
      nsPrefix="Implementation.Components">
    <eClassifiers xsi:type="ecore:EClass" name="Room"/>
    <eClassifiers xsi:type="ecore:EClass" name="Room_Room">
      <eOperations name="createRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="editRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="remove" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="countNumberOfTotalRooms" ordered="false" lowerBound="1"/>
      <eOperations name="searchRoom" ordered="false" lowerBound="1">
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getRoomTypes" ordered="false" lowerBound="1"/>
      <eOperations name="getRoomInfo" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomNumber" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usable" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomTypeName" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Room_Bedroom" eSuperTypes="#//Components/Room_Room">
      <eOperations name="createBedroom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="bedCount" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="editRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="bedCount" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedCount" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Room_ConferenceRoom" eSuperTypes="#//Components/Room_Room">
      <eOperations name="createConferenceRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="numberOfSeats" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="projector" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="conferenceRoom" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
      <eOperations name="editRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="numberOfSeats" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="projector" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="conferencePhone" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSeats" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="projector" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="conferencePhone" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaffAdministration"/>
    <eClassifiers xsi:type="ecore:EClass" name="StaffAdministration_AccountManager"
        eSuperTypes="#//InterfaceClasses/IAuthentication #//InterfaceClasses/IAccountManager">
      <eOperations name="findAccount" ordered="false" lowerBound="1" eType="#//Components/StaffAdministration_Employee">
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StaffAdministration_Employee">
      <eOperations name="Employee" ordered="false" lowerBound="1">
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="phone" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="Employee" ordered="false" lowerBound="1"/>
      <eOperations name="getEmployeeInfo" ordered="false" lowerBound="1" eType="#//Components/StaffAdministration_Employee">
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
          eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Booking"/>
    <eClassifiers xsi:type="ecore:EClass" name="Booking_BookingInterface" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Booking_PaymentDetails">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ccNumber" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ccv" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expiryMonth" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expiryYear" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Booking_Receipt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Booking_Quote"/>
    <eClassifiers xsi:type="ecore:EClass" name="Booking_Booking">
      <eOperations name="BookingObject" ordered="false" lowerBound="1"/>
      <eOperations name="Booking" ordered="false" lowerBound="1">
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="#//Components/Booking_Date"/>
        <eParameters name="departureDate" ordered="false" lowerBound="1" eType="#//Components/Booking_Date"/>
      </eOperations>
      <eOperations name="addToBooking" ordered="false" lowerBound="1">
        <eParameters name="newService" ordered="false" lowerBound="1" eType="#//Components/Booking_AdditionalService"/>
      </eOperations>
      <eOperations name="Booking" ordered="false" lowerBound="1">
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="customerSSN" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerFirstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerLastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerAddress" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerEmail" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="addToBooking" ordered="false" lowerBound="1">
        <eParameters name="newService" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="removeFromBooking" ordered="false" lowerBound="1">
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="updateBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="#//Components/Booking_Date"/>
        <eParameters name="departureDate" ordered="false" lowerBound="1" eType="#//Components/Booking_Date"/>
        <eParameters name="customerInformation" ordered="false" lowerBound="1" eType="#//Components/Booking_Person"/>
      </eOperations>
      <eOperations name="removeFromBooking" ordered="false" lowerBound="1">
        <eParameters name="additionalService" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="currentCost" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eOperations name="updatePaymentDetails" ordered="false" lowerBound="1">
        <eParameters name="newPaymentDetails" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrivalDate" ordered="false"
          lowerBound="1" eType="#//Components/Booking_Date" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="departureDate" ordered="false"
          lowerBound="1" eType="#//Components/Booking_Date" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceNumber" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guests" ordered="false"
          upperBound="-1" eType="#//Components/Booking_Person" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentCost" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rooms" ordered="false"
          lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="additionalSerivces" ordered="false"
          upperBound="-1" eType="#//Components/Booking_AdditionalService" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Booking_Date">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Day" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Month" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Year" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Booking_Person">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Booking_AdditionalService">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Booking_BookingManager">
      <eOperations name="BookingManager" ordered="false" lowerBound="1"/>
      <eOperations name="searchForBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="cancelBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="updateBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="#//Components/Booking_Date"/>
        <eParameters name="departureDate" ordered="false" lowerBound="1" eType="#//Components/Booking_Date"/>
        <eParameters name="customerInformation" ordered="false" lowerBound="1" eType="#//Components/Booking_Person"/>
      </eOperations>
      <eOperations name="addToBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="addToBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="additionalService" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="generateReceipt" ordered="false" lowerBound="1">
        <eParameters name="referenceNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="generateQuote" ordered="false" lowerBound="1">
        <eParameters name="startDate" ordered="false" lowerBound="1" eType="#//Components/Booking_Date"/>
        <eParameters name="endDate" ordered="false" lowerBound="1" eType="#//Components/Booking_Date"/>
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="removeFromBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="removeFromBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="additionalService" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="makeBooking" ordered="false" lowerBound="1">
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="customerSSN" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerFirstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerLastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerAddress" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerEmail" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="validate" ordered="false" lowerBound="1">
        <eParameters name="referenceNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="guestNames" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bookings" ordered="false"
          upperBound="-1" eType="#//Components/Booking_Booking"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AdditionalService"/>
    <eClassifiers xsi:type="ecore:EClass" name="AdditionalService_AdditionalService">
      <eOperations name="getAdditionalServiceInfo" ordered="false" lowerBound="1">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="removeAdditionalService" ordered="false" lowerBound="1">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="editAdditionalService" ordered="false" lowerBound="1">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="newName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="maxAttendants" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="addAdditionalService" ordered="false" lowerBound="1">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="maxAttendants" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usable" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAttendant" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AdditionalService_AdditionalServiceEvent">
      <eOperations name="getAdditionalServiceInfo" ordered="false" lowerBound="1">
        <eParameters name="addtionalServiceName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAttendant" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Payment"/>
    <eClassifiers xsi:type="ecore:EClass" name="Payment_PaymentManager">
      <eOperations name="makePayment" ordered="false" lowerBound="1">
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="amount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="expireMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="isCreditCardValid" ordered="false" lowerBound="1">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentDetails" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Payment_PaymentCalculator">
      <eOperations name="calculate" ordered="false" lowerBound="1">
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="additionalService" ordered="false" upperBound="-1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="checkInDate" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="checkOutDate" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="isLateCancellation" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
      </eOperations>
      <eOperations name="checkLateCancellation" ordered="false" lowerBound="1">
        <eParameters name="cancelDate" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="details" ordered="false"
          lowerBound="1" upperBound="-1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Payment_PaymentHistoryDB">
      <eOperations name="createPaymentHistory" ordered="false" lowerBound="1">
        <eParameters name="amount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="paymentDateAndTime" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="searchForPayment" ordered="false" lowerBound="1">
        <eParameters name="paymentDate" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentHistory" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Occupancy"/>
    <eClassifiers xsi:type="ecore:EClass" name="Occupancy_Occupancy">
      <eOperations name="Occupancy" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="checkInDateTime" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="Guest" ordered="false" lowerBound="1" eType="#//Components/Occupancy_Guest"/>
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomNumber" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkInDateTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOutDateTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Guest" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//Components/Occupancy_Guest"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bookingReference" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Occupancy_Guest">
      <eOperations name="Guest" ordered="false" lowerBound="1">
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
          lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Occupancy_OccupancyHandler" eSuperTypes="#//InterfaceClasses/OccupancyClientProvides">
      <eOperations name="checkInGuest" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="checkOutGuest" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="listFreeRooms" ordered="false" lowerBound="1"/>
      <eOperations name="numberOfGuestsInHotel" ordered="false" lowerBound="1"/>
      <eOperations name="listGuestsInRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Occupancy" ordered="false"
          upperBound="-1" eType="#//Components/Occupancy_Occupancy"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomerStub"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReceptionistStub"/>
    <eClassifiers xsi:type="ecore:EClass" name="AdministratorStub"/>
  </eSubpackages>
  <eSubpackages name="InterfaceClasses" nsURI="http:///Implementation/InterfaceClasses.ecore"
      nsPrefix="Implementation.InterfaceClasses">
    <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceAdmin" abstract="true"
        interface="true">
      <eOperations name="createAdditionalService" ordered="false" lowerBound="1">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="maxAttendants" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="editAdditionalService" ordered="false" lowerBound="1">
        <eParameters name="oldName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="maxAttendants" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="removeAdditionalService" ordered="false" lowerBound="1">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceClient" abstract="true"
        interface="true">
      <eOperations name="getAdditionalServiceInfo" ordered="false" lowerBound="1">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="getAllAdditionalServices" ordered="false" lowerBound="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomAdminProvides" abstract="true"
        interface="true">
      <eOperations name="createRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="editRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="usable" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="description" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="remove" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomClientProvides" abstract="true"
        interface="true">
      <eOperations name="getRoomInfo" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="searchRoom" ordered="false" lowerBound="1">
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="getRoomInfo" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="searchRoom" ordered="false" lowerBound="1">
        <eParameters name="roomTypeName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getRoomTypes" ordered="false" lowerBound="1"/>
      <eOperations name="getAllRoomNumbers" ordered="false" lowerBound="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BookingClientProvides" abstract="true"
        interface="true">
      <eOperations name="searchRooms" ordered="false" lowerBound="1">
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eOperations>
      <eOperations name="makeBooking" ordered="false" lowerBound="1">
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="customerSSN" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerFirstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerLastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerAddress" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="customerEmail" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="addRoom" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="roomId" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="requestQuote" ordered="false" lowerBound="1">
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eOperations>
      <eOperations name="editBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="roomId" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="arrivalDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="departureDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="customerId" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="cancelBooking" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="addAdditionalService" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="additionalServiceName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="removeRoom" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="roomId" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="removeAddionalService" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="additionalServiceName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="getBookingInfo" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="generateReceipt" ordered="false" lowerBound="1">
        <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="validateReferenceNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String">
        <eParameters name="referenceNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PaymentClientProvides" abstract="true"
        interface="true">
      <eOperations name="payForBooking" ordered="false" lowerBound="1">
        <eParameters name="amount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="reserveFunds" ordered="false" lowerBound="1">
        <eParameters name="amount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="unreserveFunds" ordered="false" lowerBound="1">
        <eParameters name="amount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OccupancyClientProvides" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IAccountManager" abstract="true" interface="true">
      <eOperations name="createAccount" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="email" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="phone" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="editAccountDetails" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String">
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="removeAccount" ordered="false" lowerBound="1">
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IAuthentication" abstract="true" interface="true">
      <eOperations name="logIn" ordered="false" lowerBound="1">
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="logOut" ordered="false" lowerBound="1">
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="isLoggedIn" ordered="false" lowerBound="1">
        <eParameters name="ssn" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eSubpackages name="RealizationsComponentDiagram" nsURI="http:///Implementation/InterfaceClasses/RealizationsComponentDiagram.ecore"
        nsPrefix="Implementation.InterfaceClasses.RealizationsComponentDiagram">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Realizations (ComponentDiagram)"/>
      </eAnnotations>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="InterfaceDiagrams" nsURI="http:///Implementation/InterfaceDiagrams.ecore"
      nsPrefix="Implementation.InterfaceDiagrams"/>
  <eSubpackages name="SequenceDiagrams" nsURI="http:///Implementation/SequenceDiagrams.ecore"
      nsPrefix="Implementation.SequenceDiagrams">
    <eClassifiers xsi:type="ecore:EClass" name="Search"/>
    <eClassifiers xsi:type="ecore:EClass" name="Booking"/>
    <eClassifiers xsi:type="ecore:EClass" name="CheckInGuest"/>
    <eClassifiers xsi:type="ecore:EClass" name="CheckOutGuest"/>
    <eClassifiers xsi:type="ecore:EClass" name="CancelBooking">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Cancel Booking"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="BankingModel" nsURI="http:///Implementation/BankingModel.ecore"
      nsPrefix="Implementation.BankingModel">
    <eClassifiers xsi:type="ecore:EClass" name="BankComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="AdministratorProvides" abstract="true"
        interface="true">
      <eOperations name="makeDeposit" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="sum" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eOperations name="addCreditCard" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="removeCreditCard" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="getBalance" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomerProvides" abstract="true"
        interface="true">
      <eOperations name="makePayment" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="sum" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eOperations name="isCreditCardValid" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
