<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Occupancy" nsURI="http:///Occupancy.ecore" nsPrefix="Occupancy">
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent_Occupancy">
    <eOperations name="Occupancy" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="checkInDateTime" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="Guest" ordered="false" lowerBound="1" eType="#//OccupancyComponent_Guest"/>
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomNumber" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkInDateTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOutDateTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Guest" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//OccupancyComponent_Guest"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bookingReference" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent_Guest">
    <eOperations name="Guest" ordered="false" lowerBound="1">
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent_IOccupancy" abstract="true"
      interface="true">
    <eOperations name="checkInGuest" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="checkOutGuest" ordered="false" lowerBound="1">
      <eParameters name="bookingReference" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="listFreeRooms" ordered="false" lowerBound="1"/>
    <eOperations name="listGuestsInRoom" ordered="false" lowerBound="1">
      <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="numberOfGuestsInHotel" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccupancyComponent_OccupancyHandler"
      eSuperTypes="#//OccupancyComponent_IOccupancy"/>
</ecore:EPackage>
