<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AdditionalService" nsURI="http:///AdditionalService.ecore" nsPrefix="AdditionalService">
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent_AdditionalService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usable" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAttendant" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent_AdditionalServiceEvent">
    <eOperations name="getAdditionalServiceInfo" ordered="false" lowerBound="1">
      <eParameters name="addtionalServiceName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAttendant" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent_IAdditionalServiceAdministration"
      abstract="true" interface="true">
    <eOperations name="createAdditionalService" ordered="false" lowerBound="1">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="maxAttendants" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="editAdditionalService" ordered="false" lowerBound="1">
      <eParameters name="oldName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      <eParameters name="price" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
      <eParameters name="maxAttendants" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    </eOperations>
    <eOperations name="removeAdditionalService" ordered="false" lowerBound="1">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalServiceComponent_IAdditionalServiceInformation"
      abstract="true" interface="true">
    <eOperations name="getAdditionalServiceInfo" ordered="false" lowerBound="1">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    </eOperations>
    <eOperations name="getAllAdditionalServices" ordered="false" lowerBound="1"/>
  </eClassifiers>
</ecore:EPackage>
